/**
 * Generated official plugin catalog. DO NOT EDIT.
 */
import type { GeneratedOfficialPluginCatalog } from '@prodivix/plugin-package';

export const GENERATED_OFFICIAL_PLUGIN_CATALOG = {
  schemaVersion: '1.0',
  catalogId: 'mui',
  pluginId: '@prodivix/plugin-mui',
  displayName: 'Material UI',
  description:
    'Official Material UI 7 component integration for React Blueprint projects.',
  libraryId: 'mui',
  scope: 'component',
  package: {
    name: '@mui/material',
    version: '7.3.2',
    license: 'MIT',
  },
  support: {
    total: 20,
    supported: 16,
    template: 1,
    degraded: 3,
  },
  components: [
    {
      path: 'Button',
      exportName: 'Button',
      runtimeType: 'MuiButton',
      paletteItemId: 'mui-button',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'TextField',
      exportName: 'TextField',
      runtimeType: 'MuiTextField',
      paletteItemId: 'mui-text-field',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Checkbox',
      exportName: 'Checkbox',
      runtimeType: 'MuiCheckbox',
      paletteItemId: 'mui-checkbox',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Radio',
      exportName: 'Radio',
      runtimeType: 'MuiRadio',
      paletteItemId: 'mui-radio',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Switch',
      exportName: 'Switch',
      runtimeType: 'MuiSwitch',
      paletteItemId: 'mui-switch',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Slider',
      exportName: 'Slider',
      runtimeType: 'MuiSlider',
      paletteItemId: 'mui-slider',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Card',
      exportName: 'Card',
      runtimeType: 'MuiCard',
      paletteItemId: 'mui-card',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Paper',
      exportName: 'Paper',
      runtimeType: 'MuiPaper',
      paletteItemId: 'mui-paper',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Accordion',
      exportName: 'Accordion',
      runtimeType: 'MuiAccordion',
      paletteItemId: 'mui-accordion',
      support: 'template',
      creation: 'template',
    },
    {
      path: 'AccordionSummary',
      exportName: 'AccordionSummary',
      runtimeType: 'MuiAccordionSummary',
      support: 'supported',
      creation: 'template-only',
    },
    {
      path: 'AccordionDetails',
      exportName: 'AccordionDetails',
      runtimeType: 'MuiAccordionDetails',
      support: 'supported',
      creation: 'template-only',
    },
    {
      path: 'Tabs',
      exportName: 'Tabs',
      runtimeType: 'MuiTabs',
      paletteItemId: 'mui-tabs',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Box',
      exportName: 'Box',
      runtimeType: 'MuiBox',
      paletteItemId: 'mui-box',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Stack',
      exportName: 'Stack',
      runtimeType: 'MuiStack',
      paletteItemId: 'mui-stack',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Grid',
      exportName: 'Grid',
      runtimeType: 'MuiGrid',
      paletteItemId: 'mui-grid',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Container',
      exportName: 'Container',
      runtimeType: 'MuiContainer',
      paletteItemId: 'mui-container',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Alert',
      exportName: 'Alert',
      runtimeType: 'MuiAlert',
      paletteItemId: 'mui-alert',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Snackbar',
      exportName: 'Snackbar',
      runtimeType: 'MuiSnackbar',
      paletteItemId: 'mui-snackbar',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Dialog',
      exportName: 'Dialog',
      runtimeType: 'MuiDialog',
      paletteItemId: 'mui-dialog',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'CircularProgress',
      exportName: 'CircularProgress',
      runtimeType: 'MuiCircularProgress',
      paletteItemId: 'mui-circular-progress',
      support: 'supported',
      creation: 'direct',
    },
  ],
  hostImplementations: [
    {
      id: 'mui.components',
      kind: 'component-library',
    },
    {
      id: 'mui.palette',
      kind: 'palette-projection',
    },
    {
      id: 'mui.render',
      kind: 'render-policy',
    },
    {
      id: 'mui.icons',
      kind: 'icon-provider',
    },
  ],
} as const satisfies GeneratedOfficialPluginCatalog;
