import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Alert,
  Box,
  Button,
  Card,
  Checkbox,
  CircularProgress,
  Container,
  Dialog,
  Grid,
  Paper,
  Radio,
  Slider,
  Snackbar,
  Stack,
  Switch,
  Tabs,
  TextField,
} from '@mui/material';
import type { ElementType } from 'react';

export const MUI_PACKAGE_NAME = '@mui/material';
export const MUI_PACKAGE_VERSION = '7.3.2';

export const MUI_COMPONENT_DEFINITIONS = Object.freeze([
  Object.freeze({
    path: 'Button',
    exportName: 'Button',
    runtimeType: 'MuiButton',
    paletteItemId: 'mui-button',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'TextField',
    exportName: 'TextField',
    runtimeType: 'MuiTextField',
    paletteItemId: 'mui-text-field',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Checkbox',
    exportName: 'Checkbox',
    runtimeType: 'MuiCheckbox',
    paletteItemId: 'mui-checkbox',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Radio',
    exportName: 'Radio',
    runtimeType: 'MuiRadio',
    paletteItemId: 'mui-radio',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Switch',
    exportName: 'Switch',
    runtimeType: 'MuiSwitch',
    paletteItemId: 'mui-switch',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Slider',
    exportName: 'Slider',
    runtimeType: 'MuiSlider',
    paletteItemId: 'mui-slider',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Card',
    exportName: 'Card',
    runtimeType: 'MuiCard',
    paletteItemId: 'mui-card',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Paper',
    exportName: 'Paper',
    runtimeType: 'MuiPaper',
    paletteItemId: 'mui-paper',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Accordion',
    exportName: 'Accordion',
    runtimeType: 'MuiAccordion',
    paletteItemId: 'mui-accordion',
    support: 'template',
    creation: 'template',
  }),
  Object.freeze({
    path: 'AccordionSummary',
    exportName: 'AccordionSummary',
    runtimeType: 'MuiAccordionSummary',
    support: 'supported',
    creation: 'template-only',
  }),
  Object.freeze({
    path: 'AccordionDetails',
    exportName: 'AccordionDetails',
    runtimeType: 'MuiAccordionDetails',
    support: 'supported',
    creation: 'template-only',
  }),
  Object.freeze({
    path: 'Tabs',
    exportName: 'Tabs',
    runtimeType: 'MuiTabs',
    paletteItemId: 'mui-tabs',
    support: 'degraded',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Box',
    exportName: 'Box',
    runtimeType: 'MuiBox',
    paletteItemId: 'mui-box',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Stack',
    exportName: 'Stack',
    runtimeType: 'MuiStack',
    paletteItemId: 'mui-stack',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Grid',
    exportName: 'Grid',
    runtimeType: 'MuiGrid',
    paletteItemId: 'mui-grid',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Container',
    exportName: 'Container',
    runtimeType: 'MuiContainer',
    paletteItemId: 'mui-container',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Alert',
    exportName: 'Alert',
    runtimeType: 'MuiAlert',
    paletteItemId: 'mui-alert',
    support: 'supported',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Snackbar',
    exportName: 'Snackbar',
    runtimeType: 'MuiSnackbar',
    paletteItemId: 'mui-snackbar',
    support: 'degraded',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'Dialog',
    exportName: 'Dialog',
    runtimeType: 'MuiDialog',
    paletteItemId: 'mui-dialog',
    support: 'degraded',
    creation: 'direct',
  }),
  Object.freeze({
    path: 'CircularProgress',
    exportName: 'CircularProgress',
    runtimeType: 'MuiCircularProgress',
    paletteItemId: 'mui-circular-progress',
    support: 'supported',
    creation: 'direct',
  }),
] as const);

export type MuiComponentExportName =
  (typeof MUI_COMPONENT_DEFINITIONS)[number]['exportName'];

export const MUI_COMPONENTS: Readonly<
  Record<MuiComponentExportName, ElementType>
> = Object.freeze({
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Alert,
  Box,
  Button,
  Card,
  Checkbox,
  CircularProgress,
  Container,
  Dialog,
  Grid,
  Paper,
  Radio,
  Slider,
  Snackbar,
  Stack,
  Switch,
  Tabs,
  TextField,
});
