export {
  decodeVerificationBaselineSet,
  decodeVerificationDocument,
  decodeVerificationPolicy,
  encodeVerificationBaselineSet,
  encodeVerificationDocument,
  encodeVerificationPolicy,
  isVerificationBaselineSet,
  isVerificationPolicy,
  migrateVerificationDocumentWire,
  normalizeVerificationBaselineSet,
  normalizeVerificationPolicy,
  validateVerificationDocument,
} from './verificationCodec';
export {
  VERIFICATION_DIAGNOSTIC_CODES,
  VERIFICATION_DIAGNOSTIC_REGISTRY,
} from './verificationDiagnosticRegistry';
export {
  verificationBaselineSetWireSchema,
  verificationDocumentWireSchemas,
  verificationPolicyWireSchema,
} from './wire';
export type {
  VerificationAdapter,
  VerificationAdapterBudgets,
  VerificationAdapterDescriptor,
  VerificationAdapterIdentity,
  VerificationArtifactKind,
  VerificationArtifactManifest,
  VerificationAttemptOutcome,
  VerificationAbortSignal,
  VerificationBaselineAssetRef,
  VerificationBaselineEntry,
  VerificationBaselineSet,
  VerificationBrowserEngine,
  VerificationCellStatus,
  VerificationCheckKind,
  VerificationClosure,
  VerificationClosureVerdict,
  VerificationColorScheme,
  VerificationDecodeIssue,
  VerificationDecodeResult,
  VerificationDocumentByKind,
  VerificationDocumentKind,
  VerificationEvidence,
  VerificationEvidenceRequirements,
  VerificationEvidenceTrust,
  VerificationExemption,
  VerificationImpactSet,
  VerificationImplementationIdentity,
  VerificationInputKind,
  VerificationJsonValue,
  VerificationMatrix,
  VerificationMatrixProfile,
  VerificationMotion,
  VerificationPartitionRevisions,
  VerificationPlan,
  VerificationPlanBudgets,
  VerificationPlanCell,
  VerificationPolicy,
  VerificationPolicyRequirement,
  VerificationPolicyRule,
  VerificationRequirement,
  VerificationRetryPolicy,
  VerificationRetentionClass,
  VerificationRunContext,
  VerificationCheckReportCandidate,
  VerificationPreflightResult,
  VerificationSurface,
  VerificationViewportAxis,
  VerificationWireDocument,
} from './verification.types';
export type { VerificationDiagnosticCode } from './verificationDiagnosticRegistry';
