export {
  decodeVerificationBaselineSet,
  decodeVerificationDocument,
  decodeVerificationPolicy,
  encodeVerificationBaselineSet,
  encodeVerificationDocument,
  encodeVerificationPolicy,
  isVerificationBaselineSet,
  isVerificationPolicy,
  migrateVerificationDocumentWire,
  normalizeVerificationBaselineSet,
  normalizeVerificationPolicy,
  validateVerificationDocument,
} from './verificationCodec';
export {
  VERIFICATION_DIAGNOSTIC_CODES,
  VERIFICATION_DIAGNOSTIC_REGISTRY,
} from './verificationDiagnosticRegistry';
export {
  compareVerificationText,
  digestVerificationValue,
  parseVerificationInstant,
  serializeVerificationValue,
  uniqueVerificationText,
} from './verificationCanonical';
export { createVerificationImpactSet } from './verificationImpact';
export { evaluateVerificationPolicy } from './verificationPolicyEvaluator';
export { createVerificationPlan } from './verificationPlanner';
export {
  evaluateVerificationClosure,
  isVerificationClosureForPlan,
} from './verificationClosure';
export { projectVerificationPlanExplanation } from './verificationExplanation';
export {
  verificationBaselineSetWireSchema,
  verificationDocumentWireSchemas,
  verificationPolicyWireSchema,
} from './wire';
export type {
  VerificationAdapter,
  VerificationAdapterBudgets,
  VerificationAdapterDescriptor,
  VerificationAdapterIdentity,
  VerificationArtifactKind,
  VerificationArtifactManifest,
  VerificationAttemptOutcome,
  VerificationAbortSignal,
  VerificationBaselineAssetRef,
  VerificationBaselineEntry,
  VerificationBaselineSet,
  VerificationBrowserEngine,
  VerificationCellStatus,
  VerificationCheckKind,
  VerificationClosure,
  VerificationClosureIssue,
  VerificationClosureResult,
  VerificationClosureVerdict,
  VerificationColorScheme,
  VerificationDecodeIssue,
  VerificationDecodeResult,
  VerificationDocumentByKind,
  VerificationDocumentKind,
  VerificationEvidence,
  VerificationEvidenceRequirements,
  VerificationEvidenceTrust,
  VerificationExemption,
  VerificationImpactSet,
  VerificationImpactCompleteness,
  VerificationImpactContribution,
  VerificationImpactPath,
  VerificationImpactReason,
  VerificationImpactReasonKind,
  VerificationImpactRelationship,
  VerificationImpactSetResult,
  VerificationImplementationIdentity,
  VerificationInputKind,
  VerificationJsonValue,
  VerificationMatrix,
  VerificationMatrixAxis,
  VerificationMatrixProfile,
  VerificationMotion,
  VerificationPartitionRevisions,
  VerificationPlan,
  VerificationPlanBudgetSummary,
  VerificationPlanBudgets,
  VerificationPlanCell,
  VerificationPlanCellPreflight,
  VerificationPlanIssue,
  VerificationPlanExplanation,
  VerificationPlanResource,
  VerificationPlanResult,
  VerificationPlanSelectionExplanation,
  VerificationPolicy,
  VerificationPolicyEvaluation,
  VerificationPolicyEvaluationFacts,
  VerificationPolicyEvaluationResult,
  VerificationPolicyEvaluationTrace,
  VerificationPolicyRequirement,
  VerificationPolicyRule,
  VerificationRequirement,
  VerificationRetryPolicy,
  VerificationRetentionClass,
  VerificationRunContext,
  VerificationCheckReportCandidate,
  VerificationPreflightResult,
  VerificationSurface,
  VerificationViewportAxis,
  VerificationWireDocument,
  CreateVerificationImpactSetInput,
  CreateVerificationPlanInput,
  EvaluateVerificationClosureInput,
  VerificationAdapterRegistration,
  VerificationCheckCost,
  VerificationCheckDefinition,
  VerificationScenarioDescriptor,
} from './verification.types';
export type { VerificationDiagnosticCode } from './verificationDiagnosticRegistry';
