import { verificationEvidenceCandidateWireSchema } from './verificationEvidenceCandidateSchema';
import { MAXIMUM_VERIFICATION_CLOSURE_EVIDENCE_RECORDS } from './verificationPlannerGraph';

export const VERIFICATION_CLOSURE_WIRE_VERSION = 1 as const;

const cellStatus = {
  enum: [
    'pending',
    'running',
    'passed',
    'failed',
    'blocked',
    'cancelled',
    'infrastructure-error',
    'unsupported',
    'not-applicable',
    'unstable',
    'stale',
    'incompatible',
    'missing',
  ],
} as const;

export const verificationClosureWireSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://prodivix.dev/schemas/verification-closure.v1.schema.json',
  title: 'VerificationClosureWire',
  type: 'object',
  required: [
    'wireVersion',
    'workspaceId',
    'targetRevision',
    'targetPartitionRevisions',
    'scenarioRegistryDigest',
    'semanticSchemaDigest',
    'providerSetDigest',
    'adapterRegistryDigest',
    'impactDigest',
    'policyRevision',
    'policyDigest',
    'compilerDigest',
    'plannerDigest',
    'policyEvaluationInstant',
    'planDigest',
    'closureEvaluationInstant',
    'evidenceSetDigest',
    'revocationRecordDigest',
    'baselineSetDigests',
    'toolchainSetDigest',
    'verdict',
    'cellStatuses',
    'evidenceDigests',
    'appliedExemptionIds',
    'issues',
    'closureDigest',
  ],
  properties: {
    wireVersion: { const: VERIFICATION_CLOSURE_WIRE_VERSION },
    workspaceId: { $ref: '#/$defs/canonicalId' },
    targetRevision: { $ref: '#/$defs/nonNegativeSafeInteger' },
    targetPartitionRevisions: { $ref: '#/$defs/partitionRevisions' },
    scenarioRegistryDigest: { $ref: '#/$defs/digest' },
    semanticSchemaDigest: { $ref: '#/$defs/digest' },
    providerSetDigest: { $ref: '#/$defs/digest' },
    adapterRegistryDigest: { $ref: '#/$defs/digest' },
    impactDigest: { $ref: '#/$defs/digest' },
    policyRevision: { $ref: '#/$defs/nonNegativeSafeInteger' },
    policyDigest: { $ref: '#/$defs/digest' },
    compilerDigest: { $ref: '#/$defs/digest' },
    plannerDigest: { $ref: '#/$defs/digest' },
    policyEvaluationInstant: { $ref: '#/$defs/instant' },
    planDigest: { $ref: '#/$defs/digest' },
    closureEvaluationInstant: { $ref: '#/$defs/instant' },
    evidenceSetDigest: { $ref: '#/$defs/digest' },
    revocationRecordDigest: { $ref: '#/$defs/digest' },
    baselineSetDigests: { $ref: '#/$defs/digestArray' },
    toolchainSetDigest: { $ref: '#/$defs/digest' },
    verdict: { enum: ['satisfied', 'unsatisfied', 'stale'] },
    cellStatuses: {
      type: 'object',
      minProperties: 1,
      maxProperties: MAXIMUM_VERIFICATION_CLOSURE_EVIDENCE_RECORDS,
      propertyNames: { $ref: '#/$defs/canonicalId' },
      additionalProperties: cellStatus,
    },
    evidenceDigests: { $ref: '#/$defs/digestArray' },
    appliedExemptionIds: { $ref: '#/$defs/idArray' },
    issues: {
      type: 'array',
      maxItems: MAXIMUM_VERIFICATION_CLOSURE_EVIDENCE_RECORDS,
      items: { $ref: '#/$defs/issue' },
    },
    closureDigest: { $ref: '#/$defs/digest' },
  },
  additionalProperties: false,
  $defs: {
    canonicalId: verificationEvidenceCandidateWireSchema.$defs.canonicalId,
    canonicalText: verificationEvidenceCandidateWireSchema.$defs.canonicalText,
    digest: verificationEvidenceCandidateWireSchema.$defs.digest,
    instant: verificationEvidenceCandidateWireSchema.$defs.instant,
    nonNegativeSafeInteger:
      verificationEvidenceCandidateWireSchema.$defs.nonNegativeSafeInteger,
    revisionPair: verificationEvidenceCandidateWireSchema.$defs.revisionPair,
    partitionRevisions:
      verificationEvidenceCandidateWireSchema.$defs.partitionRevisions,
    digestArray: {
      type: 'array',
      maxItems: MAXIMUM_VERIFICATION_CLOSURE_EVIDENCE_RECORDS,
      uniqueItems: true,
      items: { $ref: '#/$defs/digest' },
    },
    idArray: {
      type: 'array',
      maxItems: MAXIMUM_VERIFICATION_CLOSURE_EVIDENCE_RECORDS,
      uniqueItems: true,
      items: { $ref: '#/$defs/canonicalId' },
    },
    issue: {
      type: 'object',
      required: ['status', 'message', 'evidenceIds'],
      properties: {
        cellId: { $ref: '#/$defs/canonicalId' },
        status: {
          enum: [...cellStatus.enum, 'closure-stale'],
        },
        message: { $ref: '#/$defs/canonicalText' },
        evidenceIds: { $ref: '#/$defs/idArray' },
      },
      additionalProperties: false,
    },
  },
} as const;
