export { createWorkspaceSemanticIndex } from './createWorkspaceSemanticIndex';
export {
  CODE_REFERENCE_EXPORT_SYMBOL_KINDS,
  createCodeReferenceSemanticTarget,
  getCodeReferenceSemanticRole,
} from './codeReferenceSemantic';
export { createSemanticContributionProviderRegistry } from './semanticContributionProviderRegistry';
export {
  createSemanticResolutionDiagnostics,
  createSemanticStaleDiagnostic,
  SEMANTIC_RESOLUTION_DIAGNOSTIC_PROVIDER_ID,
  SEMANTIC_SNAPSHOT_DIAGNOSTIC_PROVIDER_ID,
} from './semanticDiagnostics';
export {
  CURRENT_SEMANTIC_SCHEMA_VERSION,
  createAnimationBindingScopeId,
  createAnimationBindingSymbolId,
  createAnimationDocumentScopeId,
  createAnimationTimelineScopeId,
  createAnimationTimelineSymbolId,
  createAnimationTrackSymbolId,
  createAssetSymbolId,
  createComponentContractMemberSymbolId,
  createComponentScopeId,
  createComponentSlotPropSymbolId,
  createComponentSlotScopeId,
  createComponentSymbolId,
  createComponentVariantOptionSymbolId,
  createCodeArtifactScopeId,
  createCodeArtifactSymbolId,
  createCodeSymbolId,
  createNodeGraphNodeScopeId,
  createNodeGraphNodeSymbolId,
  createNodeGraphPortSymbolId,
  createNodeGraphScopeId,
  createNodeGraphSymbolId,
  createPirDataSymbolId,
  createPirCollectionErrorScopeId,
  createPirCollectionErrorSymbolId,
  createPirCollectionIndexSymbolId,
  createPirCollectionItemSymbolId,
  createPirCollectionScopeId,
  createPirListIndexSymbolId,
  createPirListItemSymbolId,
  createPirListScopeId,
  createPirNodeScopeId,
  createPirNodeSymbolId,
  createPirParamSymbolId,
  createPirRegionSymbolId,
  createPirStateSymbolId,
  createRouteModuleScopeId,
  createRouteModuleSymbolId,
  createRouteMountSymbolId,
  createRouteParamSymbolId,
  createRouteManifestScopeId,
  createRouteScopeId,
  createRouteSymbolId,
  createSemanticId,
  createWorkspaceDocumentScopeId,
  createWorkspaceDocumentSymbolId,
  createWorkspaceScopeId,
} from './semanticIds';
export {
  createSemanticProviderSetDigest,
  createSemanticSnapshotIdentity,
  createSemanticSnapshotKey,
  createSemanticWorkspaceRevisionsKey,
  isSameSemanticSnapshotIdentity,
  isSameSemanticWorkspaceRevisions,
} from './semanticSnapshotIdentity';
export type { SemanticContributionProviderRegistry } from './semanticContributionProviderRegistry';
export type {
  CreateWorkspaceSemanticIndexInput,
  SemanticCompletion,
  SemanticCompletionsResult,
  SemanticContribution,
  SemanticContributionProvider,
  SemanticDiagnosticContribution,
  SemanticDiagnosticsResult,
  SemanticDocumentRevision,
  SemanticImpact,
  SemanticImpactResult,
  SemanticIndexBuildIssue,
  SemanticIndexBuildIssueCode,
  SemanticIndexBuildResult,
  SemanticProviderDescriptor,
  SemanticQueryContext,
  SemanticQueryOptions,
  SemanticReferenceTarget,
  SemanticReferenceDiagnosticPolicy,
  SemanticReferencesResult,
  SemanticResolutionMode,
  SemanticResolutionResult,
  SemanticResolutionStatus,
  SemanticSnapshotIdentity,
  SemanticSnapshotRevision,
  SemanticStaleResult,
  SemanticStoredResolutionStatus,
  SemanticSymbolStability,
  SemanticVisibleSymbolsResult,
  SemanticWorkspaceRevisions,
  WorkspaceDependencyContribution,
  WorkspaceDependencyEdge,
  WorkspaceDependencyKind,
  WorkspaceReferenceEdge,
  WorkspaceReferenceFact,
  WorkspaceReferenceKind,
  WorkspaceScope,
  WorkspaceScopeContribution,
  WorkspaceScopeKind,
  WorkspaceSemanticIndex,
  WorkspaceSymbol,
  WorkspaceSymbolContribution,
  WorkspaceSymbolKind,
} from './semantic.types';
