import type { NodeCatalogItem } from '../nodeCatalog';
import {
  CONTROL_IN,
  CONTROL_OUT,
  CONDITION_IN,
  CONDITION_OUT,
  DATA_IN,
  DATA_OUT,
} from '../nodeCatalogConstants';

export const dataInputNodeCatalog: NodeCatalogItem[] = [
  {
    kind: 'string',
    label: 'String',
    icon: '■',
    groupId: 'data-input',
    groupLabel: 'Data Input',
    ports: { dataOut: DATA_OUT },
    defaults: { value: 'hello', collapsed: false },
  },
  {
    kind: 'number',
    label: 'Number',
    icon: '■',
    groupId: 'data-input',
    groupLabel: 'Data Input',
    ports: { dataOut: DATA_OUT },
    defaults: { value: '42', collapsed: false },
  },
  {
    kind: 'boolean',
    label: 'Boolean',
    icon: '■',
    groupId: 'data-input',
    groupLabel: 'Data Input',
    ports: { dataOut: DATA_OUT },
    defaults: { value: 'true', collapsed: false },
  },
  {
    kind: 'object',
    label: 'Object',
    icon: '■',
    groupId: 'data-input',
    groupLabel: 'Data Input',
    ports: { dataOut: DATA_OUT },
    defaults: { value: '{\"key\":\"value\"}', collapsed: false },
  },
  {
    kind: 'array',
    label: 'Array',
    icon: '■',
    groupId: 'data-input',
    groupLabel: 'Data Input',
    ports: { dataOut: DATA_OUT },
    defaults: { value: '[1,2,3]', collapsed: false },
  },
  {
    kind: 'expression',
    label: 'Expression',
    icon: '◇',
    groupId: 'data-input',
    groupLabel: 'Data Input',
    ports: { dataOut: DATA_OUT, conditionOut: CONDITION_OUT },
    defaults: { expression: 'a > b', collapsed: false },
  },
  {
    kind: 'code',
    label: 'Code',
    icon: '○',
    groupId: 'data-input',
    groupLabel: 'Data Input',
    ports: { controlIn: CONTROL_IN, controlOut: CONTROL_OUT },
    defaults: {
      codeSize: 'md',
      collapsed: false,
    },
  },
];
