import type { NodeCatalogItem } from '../nodeCatalog';
import {
  CONDITION_IN,
  CONDITION_OUT,
  DATA_IN,
  DATA_OUT,
} from '../nodeCatalogConstants';

export const dataTransformNodeCatalog: NodeCatalogItem[] = [
  {
    kind: 'compare',
    label: 'Compare',
    icon: '◇',
    groupId: 'data-transform',
    groupLabel: 'Data Transform',
    ports: { dataIn: DATA_IN, dataOut: DATA_OUT, conditionOut: CONDITION_OUT },
    defaults: { operator: '===', value: '0' },
  },
  {
    kind: 'math',
    label: 'Math',
    icon: '■',
    groupId: 'data-transform',
    groupLabel: 'Data Transform',
    ports: { dataIn: DATA_IN, dataOut: DATA_OUT },
    defaults: { operator: '+', value: '0' },
  },
  {
    kind: 'templateString',
    label: 'Template String',
    icon: '■',
    groupId: 'data-transform',
    groupLabel: 'Data Transform',
    ports: { dataIn: DATA_IN, dataOut: DATA_OUT },
    defaults: { expression: 'Hello ${name}' },
  },
  {
    kind: 'jsonParse',
    label: 'JSON Parse',
    icon: '■',
    groupId: 'data-transform',
    groupLabel: 'Data Transform',
    ports: { dataIn: DATA_IN, dataOut: DATA_OUT },
    defaults: { value: '{"ok":true}' },
  },
  {
    kind: 'jsonStringify',
    label: 'JSON Stringify',
    icon: '■',
    groupId: 'data-transform',
    groupLabel: 'Data Transform',
    ports: { dataIn: DATA_IN, dataOut: DATA_OUT },
    defaults: { value: '{"ok":true}' },
  },
  {
    kind: 'map',
    label: 'Map',
    icon: '■',
    groupId: 'data-transform',
    groupLabel: 'Data Transform',
    ports: { dataIn: DATA_IN, dataOut: DATA_OUT },
    defaults: { expression: '(item) => item' },
  },
  {
    kind: 'filter',
    label: 'Filter',
    icon: '◇',
    groupId: 'data-transform',
    groupLabel: 'Data Transform',
    ports: { dataIn: DATA_IN, dataOut: DATA_OUT, conditionIn: CONDITION_IN },
    defaults: { expression: '(item) => true' },
  },
  {
    kind: 'reduce',
    label: 'Reduce',
    icon: '■',
    groupId: 'data-transform',
    groupLabel: 'Data Transform',
    ports: { dataIn: DATA_IN, dataOut: DATA_OUT },
    defaults: { expression: '(acc, item) => acc + item', value: '0' },
  },
];
