export {
  decodeBehaviorControlProfile,
  decodeBehaviorDocument,
  decodeBehaviorFixtureSet,
  decodeBehaviorScenario,
  encodeBehaviorControlProfile,
  encodeBehaviorDocument,
  encodeBehaviorFixtureSet,
  encodeBehaviorScenario,
  isBehaviorControlProfile,
  isBehaviorFixtureSet,
  isBehaviorScenario,
  migrateBehaviorDocumentWire,
  normalizeBehaviorControlProfile,
  normalizeBehaviorFixtureSet,
  normalizeBehaviorScenario,
  validateBehaviorDocument,
} from './behaviorCodec';
export {
  BEHAVIOR_DIAGNOSTIC_CODES,
  BEHAVIOR_DIAGNOSTIC_REGISTRY,
} from './behaviorDiagnosticRegistry';
export {
  behaviorControlProfileWireSchema,
  behaviorDocumentWireSchemas,
  behaviorFixtureSetWireSchema,
  behaviorScenarioWireSchema,
} from './wire';
export type {
  BehaviorAction,
  BehaviorAssertion,
  BehaviorControlProfile,
  BehaviorControlProfileRef,
  BehaviorDecodeIssue,
  BehaviorDecodeResult,
  BehaviorDocumentByKind,
  BehaviorDocumentDigestRef,
  BehaviorDocumentKind,
  BehaviorFixture,
  BehaviorFixtureOutcome,
  BehaviorFixtureSet,
  BehaviorFixtureTarget,
  BehaviorJsonValue,
  BehaviorObservation,
  BehaviorRecorderDraft,
  BehaviorRegistryContribution,
  BehaviorRegistryDescriptor,
  BehaviorScenario,
  BehaviorScenarioProgram,
  BehaviorSemanticTargetRef,
  BehaviorSourceRef,
  BehaviorStep,
  BehaviorStepMetadata,
  BehaviorTimeoutPolicy,
  BehaviorTrigger,
  BehaviorWireDocument,
} from './behavior.types';
export type { BehaviorDiagnosticCode } from './behaviorDiagnosticRegistry';
