import { defineConfig } from 'vitepress';

const base = process.env.VITEPRESS_BASE ?? '/';

// https://vitepress.dev/reference/site-config
export default defineConfig({
  base,
  title: 'Prodivix',
  description: '浏览器原生的语义化 Web 应用作者环境（alpha）',
  lang: 'zh-CN',
  lastUpdated: true,

  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: `${base}logo.svg` }],
    ['meta', { name: 'theme-color', content: '#5f67ee' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: 'Prodivix' }],
    [
      'meta',
      {
        property: 'og:description',
        content: '浏览器原生的语义化 Web 应用作者环境（alpha）',
      },
    ],
  ],

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'Prodivix',

    nav: [
      { text: '首页', link: '/' },
      { text: '指南', link: '/guide/introduction' },
      { text: '参考', link: '/reference/pir-spec' },
      {
        text: 'API',
        items: [
          { text: '组件库', link: '/api/components' },
          { text: 'CLI 工具', link: '/api/cli' },
          { text: '后端 API', link: '/api/backend' },
        ],
      },
      { text: 'Storybook', link: '/storybook/' },
      { text: '社区', link: '/community/contributing' },
    ],

    sidebar: {
      '/guide/': [
        {
          text: '入门',
          items: [
            { text: '简介', link: '/guide/introduction' },
            { text: '快速开始', link: '/guide/getting-started' },
            { text: '项目结构', link: '/guide/project-structure' },
          ],
        },
        {
          text: '核心概念',
          items: [{ text: 'AI 助手', link: '/guide/ai-assistant' }],
        },
      ],
      '/reference/': [
        {
          text: '规范',
          items: [
            { text: 'PIR 语法规范', link: '/reference/pir-spec' },
            {
              text: 'Workspace Semantic Index',
              link: '/reference/authoring-symbol-environment',
            },
            {
              text: '插件包与 Blueprint Template',
              link: '/reference/plugin-package-and-blueprint-template',
            },
            { text: 'Code 诊断', link: '/reference/code-diagnostics' },
            { text: 'UX 诊断', link: '/reference/ux-diagnostics' },
            { text: '错误码与诊断', link: '/reference/diagnostic-codes' },
          ],
        },
        {
          text: '错误码',
          collapsed: true,
          items: [
            {
              text: 'PIR',
              link: '/reference/diagnostics/pir',
              collapsed: true,
              items: [
                { text: 'PIR-1001', link: '/reference/diagnostics/pir-1001' },
                { text: 'PIR-1002', link: '/reference/diagnostics/pir-1002' },
                { text: 'PIR-1003', link: '/reference/diagnostics/pir-1003' },
                { text: 'PIR-2001', link: '/reference/diagnostics/pir-2001' },
                { text: 'PIR-2002', link: '/reference/diagnostics/pir-2002' },
                { text: 'PIR-2003', link: '/reference/diagnostics/pir-2003' },
                { text: 'PIR-2004', link: '/reference/diagnostics/pir-2004' },
                { text: 'PIR-2005', link: '/reference/diagnostics/pir-2005' },
                { text: 'PIR-2006', link: '/reference/diagnostics/pir-2006' },
                { text: 'PIR-2007', link: '/reference/diagnostics/pir-2007' },
                { text: 'PIR-3001', link: '/reference/diagnostics/pir-3001' },
                { text: 'PIR-3002', link: '/reference/diagnostics/pir-3002' },
                { text: 'PIR-3010', link: '/reference/diagnostics/pir-3010' },
                { text: 'PIR-4001', link: '/reference/diagnostics/pir-4001' },
                { text: 'PIR-9001', link: '/reference/diagnostics/pir-9001' },
              ],
            },
            {
              text: 'Workspace',
              link: '/reference/diagnostics/wks',
              collapsed: true,
              items: [
                { text: 'WKS-1001', link: '/reference/diagnostics/wks-1001' },
                { text: 'WKS-1002', link: '/reference/diagnostics/wks-1002' },
                { text: 'WKS-2001', link: '/reference/diagnostics/wks-2001' },
                { text: 'WKS-3001', link: '/reference/diagnostics/wks-3001' },
                { text: 'WKS-3002', link: '/reference/diagnostics/wks-3002' },
                { text: 'WKS-4001', link: '/reference/diagnostics/wks-4001' },
                { text: 'WKS-4002', link: '/reference/diagnostics/wks-4002' },
                { text: 'WKS-4003', link: '/reference/diagnostics/wks-4003' },
                { text: 'WKS-5002', link: '/reference/diagnostics/wks-5002' },
                { text: 'WKS-9001', link: '/reference/diagnostics/wks-9001' },
              ],
            },
            {
              text: 'Editor',
              link: '/reference/diagnostics/edt',
              collapsed: true,
              items: [
                { text: 'EDT-1001', link: '/reference/diagnostics/edt-1001' },
                { text: 'EDT-2001', link: '/reference/diagnostics/edt-2001' },
                { text: 'EDT-2002', link: '/reference/diagnostics/edt-2002' },
                { text: 'EDT-3001', link: '/reference/diagnostics/edt-3001' },
                { text: 'EDT-3002', link: '/reference/diagnostics/edt-3002' },
                { text: 'EDT-4001', link: '/reference/diagnostics/edt-4001' },
                { text: 'EDT-5001', link: '/reference/diagnostics/edt-5001' },
                { text: 'EDT-5002', link: '/reference/diagnostics/edt-5002' },
                { text: 'EDT-9001', link: '/reference/diagnostics/edt-9001' },
              ],
            },
            {
              text: 'UX',
              link: '/reference/diagnostics/ux',
              collapsed: true,
              items: [
                { text: 'UX-1001', link: '/reference/diagnostics/ux-1001' },
                { text: 'UX-1002', link: '/reference/diagnostics/ux-1002' },
                { text: 'UX-1003', link: '/reference/diagnostics/ux-1003' },
                { text: 'UX-1004', link: '/reference/diagnostics/ux-1004' },
                { text: 'UX-1005', link: '/reference/diagnostics/ux-1005' },
                { text: 'UX-1006', link: '/reference/diagnostics/ux-1006' },
                { text: 'UX-1007', link: '/reference/diagnostics/ux-1007' },
                { text: 'UX-1008', link: '/reference/diagnostics/ux-1008' },
                { text: 'UX-1009', link: '/reference/diagnostics/ux-1009' },
                { text: 'UX-1010', link: '/reference/diagnostics/ux-1010' },
                { text: 'UX-1011', link: '/reference/diagnostics/ux-1011' },
                { text: 'UX-1012', link: '/reference/diagnostics/ux-1012' },
                { text: 'UX-1013', link: '/reference/diagnostics/ux-1013' },
                { text: 'UX-1014', link: '/reference/diagnostics/ux-1014' },
                { text: 'UX-1015', link: '/reference/diagnostics/ux-1015' },
                { text: 'UX-1016', link: '/reference/diagnostics/ux-1016' },
                { text: 'UX-1017', link: '/reference/diagnostics/ux-1017' },
                { text: 'UX-1018', link: '/reference/diagnostics/ux-1018' },
                { text: 'UX-1019', link: '/reference/diagnostics/ux-1019' },
                { text: 'UX-1020', link: '/reference/diagnostics/ux-1020' },
                { text: 'UX-1021', link: '/reference/diagnostics/ux-1021' },
                { text: 'UX-1022', link: '/reference/diagnostics/ux-1022' },
                { text: 'UX-1023', link: '/reference/diagnostics/ux-1023' },
                { text: 'UX-1024', link: '/reference/diagnostics/ux-1024' },
                { text: 'UX-2001', link: '/reference/diagnostics/ux-2001' },
                { text: 'UX-2002', link: '/reference/diagnostics/ux-2002' },
                { text: 'UX-2003', link: '/reference/diagnostics/ux-2003' },
                { text: 'UX-2004', link: '/reference/diagnostics/ux-2004' },
                { text: 'UX-2005', link: '/reference/diagnostics/ux-2005' },
                { text: 'UX-2006', link: '/reference/diagnostics/ux-2006' },
                { text: 'UX-2007', link: '/reference/diagnostics/ux-2007' },
                { text: 'UX-2008', link: '/reference/diagnostics/ux-2008' },
                { text: 'UX-2009', link: '/reference/diagnostics/ux-2009' },
                { text: 'UX-2010', link: '/reference/diagnostics/ux-2010' },
                { text: 'UX-2011', link: '/reference/diagnostics/ux-2011' },
                { text: 'UX-2012', link: '/reference/diagnostics/ux-2012' },
                { text: 'UX-2013', link: '/reference/diagnostics/ux-2013' },
                { text: 'UX-2014', link: '/reference/diagnostics/ux-2014' },
                { text: 'UX-2015', link: '/reference/diagnostics/ux-2015' },
                { text: 'UX-2016', link: '/reference/diagnostics/ux-2016' },
                { text: 'UX-3001', link: '/reference/diagnostics/ux-3001' },
                { text: 'UX-3002', link: '/reference/diagnostics/ux-3002' },
                { text: 'UX-3003', link: '/reference/diagnostics/ux-3003' },
                { text: 'UX-3004', link: '/reference/diagnostics/ux-3004' },
                { text: 'UX-3005', link: '/reference/diagnostics/ux-3005' },
                { text: 'UX-3006', link: '/reference/diagnostics/ux-3006' },
                { text: 'UX-3007', link: '/reference/diagnostics/ux-3007' },
                { text: 'UX-3008', link: '/reference/diagnostics/ux-3008' },
                { text: 'UX-3009', link: '/reference/diagnostics/ux-3009' },
                { text: 'UX-3010', link: '/reference/diagnostics/ux-3010' },
                { text: 'UX-3011', link: '/reference/diagnostics/ux-3011' },
                { text: 'UX-3012', link: '/reference/diagnostics/ux-3012' },
                { text: 'UX-3013', link: '/reference/diagnostics/ux-3013' },
                { text: 'UX-3014', link: '/reference/diagnostics/ux-3014' },
                { text: 'UX-4001', link: '/reference/diagnostics/ux-4001' },
                { text: 'UX-4002', link: '/reference/diagnostics/ux-4002' },
                { text: 'UX-4003', link: '/reference/diagnostics/ux-4003' },
                { text: 'UX-4004', link: '/reference/diagnostics/ux-4004' },
                { text: 'UX-4005', link: '/reference/diagnostics/ux-4005' },
                { text: 'UX-4006', link: '/reference/diagnostics/ux-4006' },
                { text: 'UX-4007', link: '/reference/diagnostics/ux-4007' },
                { text: 'UX-4008', link: '/reference/diagnostics/ux-4008' },
                { text: 'UX-4009', link: '/reference/diagnostics/ux-4009' },
                { text: 'UX-4010', link: '/reference/diagnostics/ux-4010' },
                { text: 'UX-4011', link: '/reference/diagnostics/ux-4011' },
                { text: 'UX-4012', link: '/reference/diagnostics/ux-4012' },
                { text: 'UX-4013', link: '/reference/diagnostics/ux-4013' },
                { text: 'UX-4014', link: '/reference/diagnostics/ux-4014' },
                { text: 'UX-5001', link: '/reference/diagnostics/ux-5001' },
                { text: 'UX-5002', link: '/reference/diagnostics/ux-5002' },
                { text: 'UX-5003', link: '/reference/diagnostics/ux-5003' },
                { text: 'UX-5004', link: '/reference/diagnostics/ux-5004' },
                { text: 'UX-5005', link: '/reference/diagnostics/ux-5005' },
                { text: 'UX-5006', link: '/reference/diagnostics/ux-5006' },
                { text: 'UX-5007', link: '/reference/diagnostics/ux-5007' },
                { text: 'UX-5008', link: '/reference/diagnostics/ux-5008' },
                { text: 'UX-5009', link: '/reference/diagnostics/ux-5009' },
                { text: 'UX-5010', link: '/reference/diagnostics/ux-5010' },
                { text: 'UX-5011', link: '/reference/diagnostics/ux-5011' },
                { text: 'UX-5012', link: '/reference/diagnostics/ux-5012' },
                { text: 'UX-9001', link: '/reference/diagnostics/ux-9001' },
                { text: 'UX-9002', link: '/reference/diagnostics/ux-9002' },
                { text: 'UX-9003', link: '/reference/diagnostics/ux-9003' },
                { text: 'UX-9004', link: '/reference/diagnostics/ux-9004' },
                { text: 'UX-9005', link: '/reference/diagnostics/ux-9005' },
                { text: 'UX-9006', link: '/reference/diagnostics/ux-9006' },
              ],
            },
            {
              text: 'Semantic',
              link: '/reference/diagnostics/sem',
              collapsed: true,
              items: [
                { text: 'SEM-2001', link: '/reference/diagnostics/sem-2001' },
                { text: 'SEM-2002', link: '/reference/diagnostics/sem-2002' },
                { text: 'SEM-2003', link: '/reference/diagnostics/sem-2003' },
                { text: 'SEM-2004', link: '/reference/diagnostics/sem-2004' },
                { text: 'SEM-2005', link: '/reference/diagnostics/sem-2005' },
              ],
            },
            {
              text: 'Code',
              link: '/reference/diagnostics/cod',
              collapsed: true,
              items: [
                { text: 'COD-1001', link: '/reference/diagnostics/cod-1001' },
                { text: 'COD-1002', link: '/reference/diagnostics/cod-1002' },
                { text: 'COD-1003', link: '/reference/diagnostics/cod-1003' },
                { text: 'COD-1004', link: '/reference/diagnostics/cod-1004' },
                { text: 'COD-1005', link: '/reference/diagnostics/cod-1005' },
                { text: 'COD-1006', link: '/reference/diagnostics/cod-1006' },
                { text: 'COD-2001', link: '/reference/diagnostics/cod-2001' },
                { text: 'COD-2002', link: '/reference/diagnostics/cod-2002' },
                { text: 'COD-2003', link: '/reference/diagnostics/cod-2003' },
                { text: 'COD-2004', link: '/reference/diagnostics/cod-2004' },
                { text: 'COD-2010', link: '/reference/diagnostics/cod-2010' },
                { text: 'COD-2011', link: '/reference/diagnostics/cod-2011' },
                { text: 'COD-2012', link: '/reference/diagnostics/cod-2012' },
                { text: 'COD-2013', link: '/reference/diagnostics/cod-2013' },
                { text: 'COD-2014', link: '/reference/diagnostics/cod-2014' },
                { text: 'COD-2015', link: '/reference/diagnostics/cod-2015' },
                { text: 'COD-2016', link: '/reference/diagnostics/cod-2016' },
                { text: 'COD-3001', link: '/reference/diagnostics/cod-3001' },
                { text: 'COD-3002', link: '/reference/diagnostics/cod-3002' },
                { text: 'COD-3003', link: '/reference/diagnostics/cod-3003' },
                { text: 'COD-3010', link: '/reference/diagnostics/cod-3010' },
                { text: 'COD-3011', link: '/reference/diagnostics/cod-3011' },
                { text: 'COD-3012', link: '/reference/diagnostics/cod-3012' },
                { text: 'COD-3013', link: '/reference/diagnostics/cod-3013' },
                { text: 'COD-3014', link: '/reference/diagnostics/cod-3014' },
                { text: 'COD-3015', link: '/reference/diagnostics/cod-3015' },
                { text: 'COD-4001', link: '/reference/diagnostics/cod-4001' },
                { text: 'COD-4010', link: '/reference/diagnostics/cod-4010' },
                { text: 'COD-4011', link: '/reference/diagnostics/cod-4011' },
                { text: 'COD-4012', link: '/reference/diagnostics/cod-4012' },
                { text: 'COD-4013', link: '/reference/diagnostics/cod-4013' },
                { text: 'COD-4014', link: '/reference/diagnostics/cod-4014' },
                { text: 'COD-5001', link: '/reference/diagnostics/cod-5001' },
                { text: 'COD-5002', link: '/reference/diagnostics/cod-5002' },
                { text: 'COD-5010', link: '/reference/diagnostics/cod-5010' },
                { text: 'COD-5011', link: '/reference/diagnostics/cod-5011' },
                { text: 'COD-5012', link: '/reference/diagnostics/cod-5012' },
                { text: 'COD-5013', link: '/reference/diagnostics/cod-5013' },
                { text: 'COD-9001', link: '/reference/diagnostics/cod-9001' },
                { text: 'COD-9002', link: '/reference/diagnostics/cod-9002' },
              ],
            },
            {
              text: 'Codegen',
              link: '/reference/diagnostics/gen',
              collapsed: true,
              items: [
                { text: 'GEN-1001', link: '/reference/diagnostics/gen-1001' },
                { text: 'GEN-2001', link: '/reference/diagnostics/gen-2001' },
                { text: 'GEN-2002', link: '/reference/diagnostics/gen-2002' },
                { text: 'GEN-3001', link: '/reference/diagnostics/gen-3001' },
                { text: 'GEN-3002', link: '/reference/diagnostics/gen-3002' },
                { text: 'GEN-4001', link: '/reference/diagnostics/gen-4001' },
                { text: 'GEN-5001', link: '/reference/diagnostics/gen-5001' },
                { text: 'GEN-9001', link: '/reference/diagnostics/gen-9001' },
              ],
            },
            {
              text: 'API',
              link: '/reference/diagnostics/api',
              collapsed: true,
              items: [
                { text: 'API-1001', link: '/reference/diagnostics/api-1001' },
                { text: 'API-1002', link: '/reference/diagnostics/api-1002' },
                { text: 'API-2001', link: '/reference/diagnostics/api-2001' },
                { text: 'API-2002', link: '/reference/diagnostics/api-2002' },
                { text: 'API-3001', link: '/reference/diagnostics/api-3001' },
                { text: 'API-4001', link: '/reference/diagnostics/api-4001' },
                { text: 'API-4004', link: '/reference/diagnostics/api-4004' },
                { text: 'API-4009', link: '/reference/diagnostics/api-4009' },
                { text: 'API-5001', link: '/reference/diagnostics/api-5001' },
                { text: 'API-6001', link: '/reference/diagnostics/api-6001' },
                { text: 'API-9001', link: '/reference/diagnostics/api-9001' },
              ],
            },
            {
              text: 'AI',
              link: '/reference/diagnostics/ai',
              collapsed: true,
              items: [
                { text: 'AI-1001', link: '/reference/diagnostics/ai-1001' },
                { text: 'AI-1002', link: '/reference/diagnostics/ai-1002' },
                { text: 'AI-2001', link: '/reference/diagnostics/ai-2001' },
                { text: 'AI-2002', link: '/reference/diagnostics/ai-2002' },
                { text: 'AI-3001', link: '/reference/diagnostics/ai-3001' },
                { text: 'AI-4001', link: '/reference/diagnostics/ai-4001' },
                { text: 'AI-4002', link: '/reference/diagnostics/ai-4002' },
                { text: 'AI-5001', link: '/reference/diagnostics/ai-5001' },
                { text: 'AI-9001', link: '/reference/diagnostics/ai-9001' },
              ],
            },
            {
              text: 'Route',
              link: '/reference/diagnostics/rte',
              collapsed: true,
              items: [
                { text: 'RTE-1001', link: '/reference/diagnostics/rte-1001' },
                { text: 'RTE-1002', link: '/reference/diagnostics/rte-1002' },
                { text: 'RTE-2001', link: '/reference/diagnostics/rte-2001' },
                { text: 'RTE-3001', link: '/reference/diagnostics/rte-3001' },
                { text: 'RTE-3002', link: '/reference/diagnostics/rte-3002' },
                { text: 'RTE-4001', link: '/reference/diagnostics/rte-4001' },
                { text: 'RTE-9001', link: '/reference/diagnostics/rte-9001' },
              ],
            },
            {
              text: 'NodeGraph',
              link: '/reference/diagnostics/ngr',
              collapsed: true,
              items: [
                { text: 'NGR-1001', link: '/reference/diagnostics/ngr-1001' },
                { text: 'NGR-2001', link: '/reference/diagnostics/ngr-2001' },
                { text: 'NGR-2002', link: '/reference/diagnostics/ngr-2002' },
                { text: 'NGR-3001', link: '/reference/diagnostics/ngr-3001' },
                { text: 'NGR-4001', link: '/reference/diagnostics/ngr-4001' },
                { text: 'NGR-5001', link: '/reference/diagnostics/ngr-5001' },
                { text: 'NGR-9001', link: '/reference/diagnostics/ngr-9001' },
              ],
            },
            {
              text: 'Animation',
              link: '/reference/diagnostics/ani',
              collapsed: true,
              items: [
                { text: 'ANI-1001', link: '/reference/diagnostics/ani-1001' },
                { text: 'ANI-1002', link: '/reference/diagnostics/ani-1002' },
                { text: 'ANI-2001', link: '/reference/diagnostics/ani-2001' },
                { text: 'ANI-3001', link: '/reference/diagnostics/ani-3001' },
                { text: 'ANI-3002', link: '/reference/diagnostics/ani-3002' },
                { text: 'ANI-4001', link: '/reference/diagnostics/ani-4001' },
                { text: 'ANI-5001', link: '/reference/diagnostics/ani-5001' },
                { text: 'ANI-9001', link: '/reference/diagnostics/ani-9001' },
              ],
            },
          ],
        },
      ],
      '/api/': [
        {
          text: 'API 参考',
          items: [
            { text: '组件库', link: '/api/components' },
            { text: 'CLI 工具', link: '/api/cli' },
            { text: '后端 API', link: '/api/backend' },
          ],
        },
      ],
      '/community/': [
        {
          text: '社区',
          items: [
            { text: '贡献指南', link: '/community/contributing' },
            { text: '开发指南', link: '/community/development' },
            { text: '更新日志', link: '/community/changelog' },
          ],
        },
      ],
    },

    socialLinks: [
      {
        icon: 'github',
        link: 'https://github.com/Mdr-Tutorials/prodivix',
      },
    ],

    footer: {
      message: '基于 MIT 许可证发布',
      copyright: 'Copyright © 2024-present Prodivix Team',
    },

    search: {
      provider: 'local',
      options: {
        translations: {
          button: {
            buttonText: '搜索文档',
            buttonAriaLabel: '搜索文档',
          },
          modal: {
            noResultsText: '无法找到相关结果',
            resetButtonTitle: '清除查询条件',
            footer: {
              selectText: '选择',
              navigateText: '切换',
            },
          },
        },
      },
    },

    outline: {
      label: '页面导航',
      level: [2, 3],
    },

    docFooter: {
      prev: '上一页',
      next: '下一页',
    },

    lastUpdated: {
      text: '最后更新于',
      formatOptions: {
        dateStyle: 'short',
        timeStyle: 'medium',
      },
    },

    returnToTopLabel: '回到顶部',
    sidebarMenuLabel: '菜单',
    darkModeSwitchLabel: '主题',
    lightModeSwitchTitle: '切换到浅色模式',
    darkModeSwitchTitle: '切换到深色模式',
  },
});
