/**
 * Generated official plugin catalog. DO NOT EDIT.
 */
import type { GeneratedOfficialPluginCatalog } from '@prodivix/plugin-package';

export const GENERATED_OFFICIAL_PLUGIN_CATALOG = {
  schemaVersion: '1.0',
  catalogId: 'radix',
  pluginId: '@prodivix/plugin-radix',
  displayName: 'Radix UI',
  description:
    'Composable, accessible Radix UI primitives with real compound templates and scoped portals.',
  libraryId: 'radix',
  scope: 'component',
  package: {
    name: '@radix-ui/react-slot',
    version: '1.3.0',
    license: 'MIT',
  },
  support: {
    total: 37,
    supported: 3,
    template: 34,
    degraded: 0,
  },
  components: [
    {
      path: 'Slot',
      exportName: 'RadixSlot',
      runtimeType: 'RadixSlot',
      paletteItemId: 'radix-slot',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Label',
      exportName: 'RadixLabel',
      runtimeType: 'RadixLabel',
      paletteItemId: 'radix-label',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Separator',
      exportName: 'RadixSeparator',
      runtimeType: 'RadixSeparator',
      paletteItemId: 'radix-separator',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Accordion.Root',
      exportName: 'AccordionRoot',
      runtimeType: 'RadixAccordionRoot',
      paletteItemId: 'radix-accordion',
      support: 'template',
      creation: 'template',
    },
    {
      path: 'Accordion.Item',
      exportName: 'AccordionItem',
      runtimeType: 'RadixAccordionItem',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Accordion.Header',
      exportName: 'AccordionHeader',
      runtimeType: 'RadixAccordionHeader',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Accordion.Trigger',
      exportName: 'AccordionTrigger',
      runtimeType: 'RadixAccordionTrigger',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Accordion.Content',
      exportName: 'AccordionContent',
      runtimeType: 'RadixAccordionContent',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Tabs.Root',
      exportName: 'TabsRoot',
      runtimeType: 'RadixTabsRoot',
      paletteItemId: 'radix-tabs',
      support: 'template',
      creation: 'template',
    },
    {
      path: 'Tabs.List',
      exportName: 'TabsList',
      runtimeType: 'RadixTabsList',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Tabs.Trigger',
      exportName: 'TabsTrigger',
      runtimeType: 'RadixTabsTrigger',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Tabs.Content',
      exportName: 'TabsContent',
      runtimeType: 'RadixTabsContent',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Dialog.Root',
      exportName: 'DialogRoot',
      runtimeType: 'RadixDialogRoot',
      paletteItemId: 'radix-dialog',
      support: 'template',
      creation: 'template',
    },
    {
      path: 'Dialog.Trigger',
      exportName: 'DialogTrigger',
      runtimeType: 'RadixDialogTrigger',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Dialog.Portal',
      exportName: 'DialogPortal',
      runtimeType: 'RadixDialogPortal',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Dialog.Overlay',
      exportName: 'DialogOverlay',
      runtimeType: 'RadixDialogOverlay',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Dialog.Content',
      exportName: 'DialogContent',
      runtimeType: 'RadixDialogContent',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Dialog.Title',
      exportName: 'DialogTitle',
      runtimeType: 'RadixDialogTitle',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Dialog.Description',
      exportName: 'DialogDescription',
      runtimeType: 'RadixDialogDescription',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Dialog.Close',
      exportName: 'DialogClose',
      runtimeType: 'RadixDialogClose',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Popover.Root',
      exportName: 'PopoverRoot',
      runtimeType: 'RadixPopoverRoot',
      paletteItemId: 'radix-popover',
      support: 'template',
      creation: 'template',
    },
    {
      path: 'Popover.Trigger',
      exportName: 'PopoverTrigger',
      runtimeType: 'RadixPopoverTrigger',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Popover.Portal',
      exportName: 'PopoverPortal',
      runtimeType: 'RadixPopoverPortal',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Popover.Content',
      exportName: 'PopoverContent',
      runtimeType: 'RadixPopoverContent',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Tooltip.Provider',
      exportName: 'TooltipProvider',
      runtimeType: 'RadixTooltipProvider',
      paletteItemId: 'radix-tooltip',
      support: 'template',
      creation: 'template',
    },
    {
      path: 'Tooltip.Root',
      exportName: 'TooltipRoot',
      runtimeType: 'RadixTooltipRoot',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Tooltip.Trigger',
      exportName: 'TooltipTrigger',
      runtimeType: 'RadixTooltipTrigger',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Tooltip.Portal',
      exportName: 'TooltipPortal',
      runtimeType: 'RadixTooltipPortal',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Tooltip.Content',
      exportName: 'TooltipContent',
      runtimeType: 'RadixTooltipContent',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Tooltip.Arrow',
      exportName: 'TooltipArrow',
      runtimeType: 'RadixTooltipArrow',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'DropdownMenu.Root',
      exportName: 'DropdownMenuRoot',
      runtimeType: 'RadixDropdownMenuRoot',
      paletteItemId: 'radix-dropdown-menu',
      support: 'template',
      creation: 'template',
    },
    {
      path: 'DropdownMenu.Trigger',
      exportName: 'DropdownMenuTrigger',
      runtimeType: 'RadixDropdownMenuTrigger',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'DropdownMenu.Portal',
      exportName: 'DropdownMenuPortal',
      runtimeType: 'RadixDropdownMenuPortal',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'DropdownMenu.Content',
      exportName: 'DropdownMenuContent',
      runtimeType: 'RadixDropdownMenuContent',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'DropdownMenu.Item',
      exportName: 'DropdownMenuItem',
      runtimeType: 'RadixDropdownMenuItem',
      support: 'template',
      creation: 'template-only',
    },
    {
      path: 'Switch.Root',
      exportName: 'SwitchRoot',
      runtimeType: 'RadixSwitchRoot',
      paletteItemId: 'radix-switch',
      support: 'template',
      creation: 'template',
    },
    {
      path: 'Switch.Thumb',
      exportName: 'SwitchThumb',
      runtimeType: 'RadixSwitchThumb',
      support: 'template',
      creation: 'template-only',
    },
  ],
  unsupportedRuntimeTypes: [
    'RadixAccordion',
    'RadixTabs',
    'RadixDialog',
    'RadixPopover',
    'RadixTooltip',
    'RadixDropdownMenu',
    'RadixSwitch',
  ],
  hostImplementations: [
    {
      id: 'radix.components',
      kind: 'component-library',
    },
    {
      id: 'radix.palette',
      kind: 'palette-projection',
    },
    {
      id: 'radix.controlled-state',
      kind: 'render-policy',
    },
    {
      id: 'radix.host-overlay',
      kind: 'render-policy',
    },
  ],
} as const satisfies GeneratedOfficialPluginCatalog;
