/**
 * Generated official plugin catalog. DO NOT EDIT.
 */
import type { GeneratedOfficialPluginCatalog } from '@prodivix/plugin-package';

export const GENERATED_OFFICIAL_PLUGIN_CATALOG = {
  schemaVersion: '1.0',
  catalogId: 'antd',
  pluginId: '@prodivix/plugin-antd',
  displayName: 'Ant Design',
  description: 'Official Ant Design components and icons for React projects.',
  libraryId: 'antd',
  scope: 'component',
  package: {
    name: 'antd',
    version: '5.28.0',
    license: 'MIT',
  },
  support: {
    total: 81,
    supported: 46,
    template: 1,
    degraded: 34,
  },
  components: [
    {
      path: 'App',
      exportName: 'App',
      runtimeType: 'AntdApp',
      paletteItemId: 'antd-app',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Button',
      exportName: 'Button',
      runtimeType: 'AntdButton',
      paletteItemId: 'antd-button',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'FloatButton',
      exportName: 'FloatButton',
      runtimeType: 'AntdFloatButton',
      paletteItemId: 'antd-float-button',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Divider',
      exportName: 'Divider',
      runtimeType: 'AntdDivider',
      paletteItemId: 'antd-divider',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Flex',
      exportName: 'Flex',
      runtimeType: 'AntdFlex',
      paletteItemId: 'antd-flex',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Layout',
      exportName: 'Layout',
      runtimeType: 'AntdLayout',
      paletteItemId: 'antd-layout',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Layout.Header',
      exportName: 'LayoutHeader',
      runtimeType: 'AntdLayoutHeader',
      paletteItemId: 'antd-layout-header',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Layout.Content',
      exportName: 'LayoutContent',
      runtimeType: 'AntdLayoutContent',
      paletteItemId: 'antd-layout-content',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Layout.Footer',
      exportName: 'LayoutFooter',
      runtimeType: 'AntdLayoutFooter',
      paletteItemId: 'antd-layout-footer',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Layout.Sider',
      exportName: 'LayoutSider',
      runtimeType: 'AntdLayoutSider',
      paletteItemId: 'antd-layout-sider',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Space',
      exportName: 'Space',
      runtimeType: 'AntdSpace',
      paletteItemId: 'antd-space',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Space.Compact',
      exportName: 'SpaceCompact',
      runtimeType: 'AntdSpaceCompact',
      paletteItemId: 'antd-space-compact',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Splitter',
      exportName: 'Splitter',
      runtimeType: 'AntdSplitter',
      paletteItemId: 'antd-splitter',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Affix',
      exportName: 'Affix',
      runtimeType: 'AntdAffix',
      paletteItemId: 'antd-affix',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Anchor',
      exportName: 'Anchor',
      runtimeType: 'AntdAnchor',
      paletteItemId: 'antd-anchor',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Breadcrumb',
      exportName: 'Breadcrumb',
      runtimeType: 'AntdBreadcrumb',
      paletteItemId: 'antd-breadcrumb',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Dropdown',
      exportName: 'Dropdown',
      runtimeType: 'AntdDropdown',
      paletteItemId: 'antd-dropdown',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Menu',
      exportName: 'Menu',
      runtimeType: 'AntdMenu',
      paletteItemId: 'antd-menu',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Pagination',
      exportName: 'Pagination',
      runtimeType: 'AntdPagination',
      paletteItemId: 'antd-pagination',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Steps',
      exportName: 'Steps',
      runtimeType: 'AntdSteps',
      paletteItemId: 'antd-steps',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Tabs',
      exportName: 'Tabs',
      runtimeType: 'AntdTabs',
      paletteItemId: 'antd-tabs',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'AutoComplete',
      exportName: 'AutoComplete',
      runtimeType: 'AntdAutoComplete',
      paletteItemId: 'antd-auto-complete',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Cascader',
      exportName: 'Cascader',
      runtimeType: 'AntdCascader',
      paletteItemId: 'antd-cascader',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Checkbox',
      exportName: 'Checkbox',
      runtimeType: 'AntdCheckbox',
      paletteItemId: 'antd-checkbox',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'ColorPicker',
      exportName: 'ColorPicker',
      runtimeType: 'AntdColorPicker',
      paletteItemId: 'antd-color-picker',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'DatePicker',
      exportName: 'DatePicker',
      runtimeType: 'AntdDatePicker',
      paletteItemId: 'antd-date-picker',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Form',
      exportName: 'Form',
      runtimeType: 'AntdForm',
      paletteItemId: 'antd-form',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Form.Item',
      exportName: 'FormItem',
      runtimeType: 'AntdFormItem',
      paletteItemId: 'antd-form-item',
      support: 'template',
      creation: 'template',
    },
    {
      path: 'Input',
      exportName: 'Input',
      runtimeType: 'AntdInput',
      paletteItemId: 'antd-input',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Input.Password',
      exportName: 'InputPassword',
      runtimeType: 'AntdInputPassword',
      paletteItemId: 'antd-input-password',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Input.Search',
      exportName: 'InputSearch',
      runtimeType: 'AntdInputSearch',
      paletteItemId: 'antd-input-search',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Input.TextArea',
      exportName: 'InputTextArea',
      runtimeType: 'AntdInputTextArea',
      paletteItemId: 'antd-input-text-area',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'InputNumber',
      exportName: 'InputNumber',
      runtimeType: 'AntdInputNumber',
      paletteItemId: 'antd-input-number',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Mentions',
      exportName: 'Mentions',
      runtimeType: 'AntdMentions',
      paletteItemId: 'antd-mentions',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Radio',
      exportName: 'Radio',
      runtimeType: 'AntdRadio',
      paletteItemId: 'antd-radio',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Rate',
      exportName: 'Rate',
      runtimeType: 'AntdRate',
      paletteItemId: 'antd-rate',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Select',
      exportName: 'Select',
      runtimeType: 'AntdSelect',
      paletteItemId: 'antd-select',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Slider',
      exportName: 'Slider',
      runtimeType: 'AntdSlider',
      paletteItemId: 'antd-slider',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Switch',
      exportName: 'Switch',
      runtimeType: 'AntdSwitch',
      paletteItemId: 'antd-switch',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'TimePicker',
      exportName: 'TimePicker',
      runtimeType: 'AntdTimePicker',
      paletteItemId: 'antd-time-picker',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Transfer',
      exportName: 'Transfer',
      runtimeType: 'AntdTransfer',
      paletteItemId: 'antd-transfer',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'TreeSelect',
      exportName: 'TreeSelect',
      runtimeType: 'AntdTreeSelect',
      paletteItemId: 'antd-tree-select',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Upload',
      exportName: 'Upload',
      runtimeType: 'AntdUpload',
      paletteItemId: 'antd-upload',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Avatar',
      exportName: 'Avatar',
      runtimeType: 'AntdAvatar',
      paletteItemId: 'antd-avatar',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Badge',
      exportName: 'Badge',
      runtimeType: 'AntdBadge',
      paletteItemId: 'antd-badge',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Calendar',
      exportName: 'Calendar',
      runtimeType: 'AntdCalendar',
      paletteItemId: 'antd-calendar',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Card',
      exportName: 'Card',
      runtimeType: 'AntdCard',
      paletteItemId: 'antd-card',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Card.Meta',
      exportName: 'CardMeta',
      runtimeType: 'AntdCardMeta',
      paletteItemId: 'antd-card-meta',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Carousel',
      exportName: 'Carousel',
      runtimeType: 'AntdCarousel',
      paletteItemId: 'antd-carousel',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Collapse',
      exportName: 'Collapse',
      runtimeType: 'AntdCollapse',
      paletteItemId: 'antd-collapse',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Descriptions',
      exportName: 'Descriptions',
      runtimeType: 'AntdDescriptions',
      paletteItemId: 'antd-descriptions',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Descriptions.Item',
      exportName: 'DescriptionsItem',
      runtimeType: 'AntdDescriptionsItem',
      paletteItemId: 'antd-descriptions-item',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Empty',
      exportName: 'Empty',
      runtimeType: 'AntdEmpty',
      paletteItemId: 'antd-empty',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Image',
      exportName: 'Image',
      runtimeType: 'AntdImage',
      paletteItemId: 'antd-image',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'List',
      exportName: 'List',
      runtimeType: 'AntdList',
      paletteItemId: 'antd-list',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'List.Item',
      exportName: 'ListItem',
      runtimeType: 'AntdListItem',
      paletteItemId: 'antd-list-item',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'List.Item.Meta',
      exportName: 'ListItemMeta',
      runtimeType: 'AntdListItemMeta',
      paletteItemId: 'antd-list-item-meta',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Popover',
      exportName: 'Popover',
      runtimeType: 'AntdPopover',
      paletteItemId: 'antd-popover',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'QRCode',
      exportName: 'QRCode',
      runtimeType: 'AntdQRCode',
      paletteItemId: 'antd-qrcode',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Segmented',
      exportName: 'Segmented',
      runtimeType: 'AntdSegmented',
      paletteItemId: 'antd-segmented',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Statistic',
      exportName: 'Statistic',
      runtimeType: 'AntdStatistic',
      paletteItemId: 'antd-statistic',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Table',
      exportName: 'Table',
      runtimeType: 'AntdTable',
      paletteItemId: 'antd-table',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Tag',
      exportName: 'Tag',
      runtimeType: 'AntdTag',
      paletteItemId: 'antd-tag',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Timeline',
      exportName: 'Timeline',
      runtimeType: 'AntdTimeline',
      paletteItemId: 'antd-timeline',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Tooltip',
      exportName: 'Tooltip',
      runtimeType: 'AntdTooltip',
      paletteItemId: 'antd-tooltip',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Tour',
      exportName: 'Tour',
      runtimeType: 'AntdTour',
      paletteItemId: 'antd-tour',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Tree',
      exportName: 'Tree',
      runtimeType: 'AntdTree',
      paletteItemId: 'antd-tree',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Typography',
      exportName: 'Typography',
      runtimeType: 'AntdTypography',
      paletteItemId: 'antd-typography',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Typography.Text',
      exportName: 'TypographyText',
      runtimeType: 'AntdTypographyText',
      paletteItemId: 'antd-typography-text',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Typography.Title',
      exportName: 'TypographyTitle',
      runtimeType: 'AntdTypographyTitle',
      paletteItemId: 'antd-typography-title',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Typography.Paragraph',
      exportName: 'TypographyParagraph',
      runtimeType: 'AntdTypographyParagraph',
      paletteItemId: 'antd-typography-paragraph',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Typography.Link',
      exportName: 'TypographyLink',
      runtimeType: 'AntdTypographyLink',
      paletteItemId: 'antd-typography-link',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Alert',
      exportName: 'Alert',
      runtimeType: 'AntdAlert',
      paletteItemId: 'antd-alert',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Drawer',
      exportName: 'Drawer',
      runtimeType: 'AntdDrawer',
      paletteItemId: 'antd-drawer',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Modal',
      exportName: 'Modal',
      runtimeType: 'AntdModal',
      paletteItemId: 'antd-modal',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Popconfirm',
      exportName: 'Popconfirm',
      runtimeType: 'AntdPopconfirm',
      paletteItemId: 'antd-popconfirm',
      support: 'degraded',
      creation: 'direct',
    },
    {
      path: 'Progress',
      exportName: 'Progress',
      runtimeType: 'AntdProgress',
      paletteItemId: 'antd-progress',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Result',
      exportName: 'Result',
      runtimeType: 'AntdResult',
      paletteItemId: 'antd-result',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Skeleton',
      exportName: 'Skeleton',
      runtimeType: 'AntdSkeleton',
      paletteItemId: 'antd-skeleton',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Spin',
      exportName: 'Spin',
      runtimeType: 'AntdSpin',
      paletteItemId: 'antd-spin',
      support: 'supported',
      creation: 'direct',
    },
    {
      path: 'Watermark',
      exportName: 'Watermark',
      runtimeType: 'AntdWatermark',
      paletteItemId: 'antd-watermark',
      support: 'supported',
      creation: 'direct',
    },
  ],
  hostImplementations: [
    {
      id: 'antd.components',
      kind: 'component-library',
    },
    {
      id: 'antd.icons',
      kind: 'icon-provider',
    },
    {
      id: 'antd.palette',
      kind: 'palette-projection',
    },
    {
      id: 'antd.render.overlay',
      kind: 'render-policy',
    },
    {
      id: 'antd.render.provider',
      kind: 'render-policy',
    },
  ],
} as const satisfies GeneratedOfficialPluginCatalog;
