export {
  generateReactBundle,
  generateReactCode,
  type ReactExportBundle,
} from '#src/pirToReact';
export { compilePirToReactComponent } from '#src/react/compileComponent';
export {
  compileWorkspaceToExportProgram,
  generateWorkspaceReactViteBundle,
  type WorkspaceReactViteCompileOptions,
} from '#src/react/workspaceProject';
export { compileAnimationExportContributions } from '#src/animation/compileAnimation';
export { compileNodeGraphExportContributions } from '#src/nodegraph/compileNodeGraph';
export type {
  ExportResourceType,
  ReactComponentCompileResult,
  ReactCompileOptions,
  ReactGeneratorCodeArtifact,
  ReactGeneratorOptions,
} from '#src/react/types';
export type { ExportFile as ReactExportFile } from '#src/export';
export {
  ProductionExportPlanner,
  ExportProgramBuilder,
  collectExportCodeArtifactContributions,
  collectExportCodeArtifactFileContributions,
  createReactViteExportPreset,
  createUniqueExportPath,
  exportArtifactToProgramContribution,
  exportArtifactsToProgramContribution,
  createExportCodeArtifactStyleArtifactContribution,
  createExportCodeArtifactStyleContribution,
  createExportProgramBuilder,
  createRouteExportContribution,
  createStyleImportIntents,
  createStaticDeploymentExportContribution,
  collectReferencedExportAssets,
  dedupeExportImportIntents,
  ensureFileExtension,
  completeExportDependencyOrigin,
  createExportPackageOrigin,
  exportDependenciesToPackageFields,
  getExportDirname,
  getExportCodeArtifactFileKind,
  getExportCodeArtifactImportMode,
  getExportCodeArtifactLanguage,
  getExportCodeArtifactMimeType,
  getRelativeImportPath,
  isExportCssCodeArtifact,
  joinExportPath,
  mergeExportDependencies,
  normalizeExportCodeArtifactPath,
  normalizeExportPath,
  planExportAssetContributions,
  planExportFileContributions,
  planExportStyleSheets,
  renderExportImportIntent,
  recordToExportDependencies,
  resolveExportSource,
  resolvePackageExportSource,
  resolvePluginExportSource,
  resolveRemoteExportSource,
  resolveVendoredExportSource,
  resolveWorkspaceDocumentExportSource,
  toSafeExportIdentifier,
  validateExportOriginPolicy,
  EXPORT_KNOWN_PACKAGE_METADATA,
} from '#src/export';
export type {
  DiagnosticTargetRef,
  ExportArtifactContribution,
  ExportArtifactKind,
  ExportArtifactPlacement,
  ExportAssetContribution,
  ExportAssetDeliveryPolicy,
  ExportBundle,
  ExportBundleMetadata,
  ExportCodeArtifact,
  ExportDeploymentContribution,
  ExportDeploymentSummary,
  ExportDeploymentTarget,
  ExportDependency,
  ExportDependencySummary,
  ExportDiagnosticSummary,
  ExportFile,
  ExportFileContribution,
  ExportFileImportMode,
  ExportFileKind,
  ExportImportIntent,
  ExportImportKind,
  ExportModule,
  ExportModuleKind,
  ExportOrderHint,
  ExportLicenseSummary,
  ExportOriginSummary,
  ExportPathRewrite,
  ExportPlannerPreset,
  ExportReferencedAsset,
  ExportProgram,
  ExportProgramContribution,
  ExportProgramMetadata,
  ExportRouteGeneratedFile,
  ExportRouteOutletBinding,
  ExportRouteRuntimeRef,
  ExportRouteRuntimeRefKind,
  ExportRouteTopology,
  ExportRouteTopologyNode,
  ExportRoot,
  ExportRootKind,
  ExportRuntimeModuleFactory,
  ExportRuntimeRequirement,
  ExportSourceOrigin,
  ExportSourceOriginKind,
  ExportSourceOwner,
  ExportSourceSummary,
  ExportSourceTrace,
  ExportSourceTraceSummary,
  ExportStyleContribution,
  ExportStyleScope,
  ExportTarget,
  ExportTargetFramework,
  ExportUpdatePolicy,
  ExportWritePolicy,
  ExportPackageMetadata,
  ExportPackageOriginOptions,
  ExportResolvedSource,
  ExportSourceResolverInput,
  ExportSourceResolverKind,
  CreateRouteExportContributionOptions,
  PlannedExportModule,
  PlannedRuntimeModule,
  PlannedStyleSheet,
  RouteExportCodeArtifactInfo,
  RouteExportDocumentInfo,
  ReserveExportPath,
  SourceSpan,
  StaticDeploymentTarget,
} from '#src/export';
export type { StaticDeploymentPresetOptions } from '#src/export';
export type { TargetAdapter } from '#src/core/adapter';
export {
  createCodegenPolicyTargetAdapter,
  getCodegenPolicyPackageMetadata,
  getCodegenPolicyPackageVersions,
  type CodegenLibraryPolicy,
  type CodegenPolicyChildren,
  type CodegenPolicyDependency,
  type CodegenPolicyPropsTransform,
  type CodegenPolicyRule,
  type CodegenPolicySnapshot,
  type CodegenPolicySource,
  type IconCodegenPolicy,
} from '#src/core/codegenPolicy';
export type { CompileDiagnostic } from '#src/core/diagnostics';
export type { PIRDocument } from '@prodivix/shared/types/pir';
