export {
  compileWorkspacePirReactModules,
  createPirReactModuleId,
  CONTROLLED_CSS_ISSUE_CODES,
  CONTROLLED_CSS_NODE_ID_ATTRIBUTE,
  CONTROLLED_CSS_NUMBER_MARKER,
  CONTROLLED_REACT_JSX_NODE_ID_ATTRIBUTE,
  CONTROLLED_REACT_JSX_ISSUE_CODES,
  CONTROLLED_ROUND_TRIP_ISSUE_CODES,
  PIR_REACT_COMPILE_DIAGNOSTIC_CODES,
  augmentWorkspaceOperationWithControlledSource,
  createControlledCodeDocumentsPlan,
  createControlledCodeEditPlan,
  createControlledSourceAttachmentPlan,
  parseControlledCssToPirDocument,
  projectPirDocumentToControlledCss,
  parseControlledReactJsxToPirDocument,
  projectPirDocumentToControlledReactJsx,
  type ControlledReactJsxIssue,
  type ControlledReactJsxIssueCode,
  type ControlledReactJsxParseResult,
  type ControlledReactJsxProjectionResult,
  type ControlledCssIssue,
  type ControlledCssIssueCode,
  type ControlledCssParseResult,
  type ControlledCssProjectionResult,
  type ControlledCodeDocumentInput,
  type ControlledRoundTripAugmentResult,
  type ControlledRoundTripIssue,
  type ControlledRoundTripIssueCode,
  type ControlledRoundTripPlanResult,
  type CompileWorkspacePirReactModulesInput,
  type PIRReactCollectionProjectionIssueReport,
  type PIRReactCodeReference,
  type PIRReactDataLifecycleSnapshotRequest,
  type PIRReactRuntimePort,
  type PIRReactStateUpdater,
  type PIRReactRuntimeTriggerDispatch,
  type WorkspacePirReactCompileBlocked,
  type WorkspacePirReactCompileReady,
  type WorkspacePirReactCompileResult,
} from '#src/react/index';
export {
  compileWorkspaceToExportProgram,
  generateWorkspaceReactViteBundle,
  type WorkspaceReactViteCompileOptions,
} from '#src/react/workspaceProject';
export {
  analyzeWorkspaceDataRuntimeTarget,
  EXECUTION_PARENT_GATEWAY_DATA_RUNTIME_TARGET,
  PROVIDER_MOCK_DATA_RUNTIME_TARGET,
  STATIC_CLIENT_DATA_RUNTIME_TARGET,
  WORKSPACE_DATA_RUNTIME_TARGET_FORMAT,
  type WorkspaceDataRuntimeRequirements,
  type WorkspaceDataRuntimeTarget,
  type WorkspaceDataRuntimeTargetAnalysis,
} from '#src/react/workspaceDataRuntimeTarget';
export {
  analyzeWorkspaceServerRuntimeTarget,
  DETERMINISTIC_TEST_SERVER_RUNTIME_TARGET,
  EXECUTION_PARENT_GATEWAY_SERVER_RUNTIME_TARGET,
  STATIC_CLIENT_SERVER_RUNTIME_TARGET,
  WORKSPACE_SERVER_RUNTIME_TARGET_FORMAT,
  type WorkspaceServerRuntimeBinding,
  type WorkspaceServerRuntimeRequirements,
  type WorkspaceServerRuntimeTarget,
  type WorkspaceServerRuntimeTargetAnalysis,
} from '#src/react/workspaceServerRuntimeTarget';
export {
  createWorkspaceStandaloneServerRuntimeModule,
  WORKSPACE_SERVER_RUNTIME_MODULE_ID,
} from '#src/react/standaloneServerRuntime';
export {
  createWorkspaceExecutionConsoleRuntimeModule,
  WORKSPACE_EXECUTION_CONSOLE_RUNTIME_MODULE_ID,
} from '#src/react/standaloneExecutionConsoleRuntime';
export {
  createWorkspaceExecutionSnapshotRef,
  generateWorkspaceReactViteExecutableProject,
  type GenerateWorkspaceExecutableProjectOptions,
  type WorkspaceExecutableProjectResult,
} from '#src/executableProject/workspaceExecutableProject';
export {
  generateWorkspaceIsolatedServerFunctionExecutableProject,
  ISOLATED_SERVER_FUNCTION_ADAPTER_ID,
  type GenerateIsolatedServerFunctionExecutableProjectOptions,
  type IsolatedServerFunctionExecutableProjectResult,
} from '#src/executableProject/isolatedServerFunctionProject';
export {
  analyzeWorkspaceRuntimeFilesystemDiff,
  createWorkspaceRuntimeFilesystemAssetUploadPlan,
  createWorkspaceRuntimeFilesystemProposal,
  type CreateWorkspaceRuntimeFilesystemAssetUploadPlanInput,
  type CreateWorkspaceRuntimeFilesystemProposalInput,
  type RuntimeFilesystemAssetUploadReceipt,
  type RuntimeFilesystemAssetUploadRequest,
  type RuntimeFilesystemProposalBlockReason,
  type RuntimeFilesystemProposalEntry,
  type WorkspaceRuntimeFilesystemProposalAnalysis,
  type WorkspaceRuntimeFilesystemProposalResult,
  type WorkspaceRuntimeFilesystemAssetUploadPlanResult,
} from '#src/executableProject/runtimeFilesystemProposal';
export { compileAnimationExportContributions } from '#src/animation/compileAnimation';
export { compileNodeGraphExportContributions } from '#src/nodegraph/compileNodeGraph';
export type {
  ExportResourceType,
  ReactExportBundle,
  ReactGeneratorCodeArtifact,
} from '#src/react/types';
export type { ExportFile as ReactExportFile } from '#src/export';
export {
  ProductionExportPlanner,
  ExportProgramBuilder,
  collectExportCodeArtifactContributions,
  collectExportCodeArtifactFileContributions,
  createReactViteExportPreset,
  createUniqueExportPath,
  exportArtifactToProgramContribution,
  exportArtifactsToProgramContribution,
  createExportCodeArtifactStyleArtifactContribution,
  createExportCodeArtifactStyleContribution,
  createExportProgramBuilder,
  createRouteExportContribution,
  createStyleImportIntents,
  createStaticDeploymentExportContribution,
  collectReferencedExportAssets,
  createWorkspaceGitAssetProjection,
  dedupeExportImportIntents,
  ensureFileExtension,
  completeExportDependencyOrigin,
  createExportPackageOrigin,
  exportDependenciesToPackageFields,
  getExportDirname,
  getExportCodeArtifactFileKind,
  getExportCodeArtifactImportMode,
  getExportCodeArtifactLanguage,
  getExportCodeArtifactMimeType,
  getRelativeImportPath,
  isExportCssCodeArtifact,
  joinExportPath,
  mergeExportDependencies,
  normalizeExportCodeArtifactPath,
  normalizeExportPath,
  planExportAssetContributions,
  planExportFileContributions,
  planExportStyleSheets,
  renderExportImportIntent,
  recordToExportDependencies,
  resolveExportSource,
  resolvePackageExportSource,
  resolvePluginExportSource,
  resolveRemoteExportSource,
  resolveVendoredExportSource,
  resolveWorkspaceDocumentExportSource,
  toSafeExportIdentifier,
  validateExportOriginPolicy,
  EXPORT_KNOWN_PACKAGE_METADATA,
} from '#src/export';
export type {
  CreateWorkspaceGitAssetProjectionInput,
  DiagnosticTargetRef,
  ExportArtifactContribution,
  ExportArtifactKind,
  ExportArtifactPlacement,
  ExportAssetContribution,
  ExportAssetDeliveryPolicy,
  ExportBundle,
  ExportBundleMetadata,
  ExportCodeArtifact,
  ExportDeploymentContribution,
  ExportDeploymentSummary,
  ExportDeploymentTarget,
  ExportDependency,
  ExportDependencySummary,
  ExportDiagnosticSummary,
  ExportFile,
  ExportFileContribution,
  ExportFileImportMode,
  ExportFileKind,
  ExportImportIntent,
  ExportImportKind,
  ExportModule,
  ExportModuleKind,
  ExportOrderHint,
  ExportLicenseSummary,
  ExportOriginSummary,
  ExportPathRewrite,
  ExportPlannerPreset,
  ExportReferencedAsset,
  ExportProgram,
  ExportProgramContribution,
  ExportProgramMetadata,
  ExportRouteGeneratedFile,
  ExportRouteOutletBinding,
  ExportRouteRuntimeRef,
  ExportRouteRuntimeRefKind,
  ExportRouteTopology,
  ExportRouteTopologyNode,
  ExportRoot,
  ExportRootKind,
  ExportRuntimeModuleFactory,
  ExportRuntimeRequirement,
  ExportSourceOrigin,
  ExportSourceOriginKind,
  ExportSourceOwner,
  ExportSourceSummary,
  ExportSourceTrace,
  ExportSourceTraceSummary,
  ExportStyleContribution,
  ExportStyleScope,
  ExportTarget,
  ExportTargetFramework,
  ExportUpdatePolicy,
  ExportWritePolicy,
  ExportPackageMetadata,
  ExportPackageOriginOptions,
  ExportResolvedSource,
  ExportSourceResolverInput,
  ExportSourceResolverKind,
  CreateRouteExportContributionOptions,
  PlannedExportModule,
  PlannedRuntimeModule,
  PlannedStyleSheet,
  RouteExportCodeArtifactInfo,
  RouteExportDocumentInfo,
  ReserveExportPath,
  SourceSpan,
  StaticDeploymentTarget,
} from '#src/export';
export type { StaticDeploymentPresetOptions } from '#src/export';
export type { TargetAdapter, TargetAdapterNode } from '#src/core/adapter';
export {
  createCodegenPolicyTargetAdapter,
  getCodegenPolicyPackageMetadata,
  getCodegenPolicyPackageVersions,
  type CodegenLibraryPolicy,
  type CodegenPolicyChildren,
  type CodegenPolicyDependency,
  type CodegenPolicyPropsTransform,
  type CodegenPolicyRule,
  type CodegenPolicySnapshot,
  type CodegenPolicySource,
  type IconCodegenPolicy,
} from '#src/core/codegenPolicy';
export type { CompileDiagnostic } from '#src/core/diagnostics';
export type { PIRDocument } from '@prodivix/pir';
